### ISSUE TITLE
I can't load my plugin list

### ISSUE THREAD

**Issue by lucianfallen** [loot/falloutnv#35] opened 2018-01-30 18:44 UTC
The program said to check LOOTDebugLog.txt
[LOOTDebugLog.txt](https://github.com/loot/falloutnv/files/1678944/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2018-01-30 18:58
This looks like a duplicate of loot/loot#858, `FreesideOpen - NewVegasBountiesIII.esp` is corrupt.

**Closed as completed** 2018-02-08 13:53 UTC
Labels: duplicate
